/* Query 01 - Var_0 Rev_01 - TPC-H/TPC-R Pricing Summary Report Query   */
SELECT
        L_RETURNFLAG,
        L_LINESTATUS,
        SUM(L_QUANTITY (FLOAT)) (DECIMAL(18,2)) AS SUM_QTY,
        SUM(L_EXTENDEDPRICE (FLOAT)) (DECIMAL(18,2)) AS SUM_BASE_PRICE,
        SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT) (FLOAT)) (DECIMAL(18,2)) AS SUM_DISC_PRICE,
        SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)*(1+L_TAX) (FLOAT)) (DECIMAL(18,2)) AS SUM_CHARGE,
        AVG(L_QUANTITY (FLOAT)) (DECIMAL(18,2)) AS AVG_QTY,
        AVG(L_EXTENDEDPRICE (FLOAT)) (DECIMAL(18,2)) AS AVG_PRICE,
        AVG(L_DISCOUNT (FLOAT)) (DECIMAL(18,2)) AS AVG_DISC,
        COUNT(*) (DEC(18,0)) AS COUNT_ORDER
FROM
        LINEITEM
WHERE
        L_SHIPDATE <= DATE '1998-12-01' - INTERVAL '77' DAY
GROUP BY
        L_RETURNFLAG,
        L_LINESTATUS
ORDER BY
        L_RETURNFLAG,
        L_LINESTATUS;
