/* QUERY 15 - VAR_0 REV_01 - TPC-H/TPC-R  TOP SUPPLIER QUERY */
WITH REVENUE(SUPPLIER_NO, TOTAL_REVENUE) AS
        (
                SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1-L_DISCOUNT) (FLOAT)) (DECIMAL(18,2))
                FROM LINEITEM
                WHERE L_SHIPDATE >= DATE '1995-04-01' AND L_SHIPDATE < DATE '1995-04-01'+ INTERVAL '3' MONTH
                GROUP BY L_SUPPKEY
        )
SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE
WHERE S_SUPPKEY = SUPPLIER_NO AND TOTAL_REVENUE = (SELECT MAX(TOTAL_REVENUE) FROM REVENUE)
ORDER BY S_SUPPKEY;